---
title: "Research"
description: |
  Research topics: fertility, birth postponement, family change, assisted reproduction, miscarriage
output: distill::distill_article
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Work in progress

- Köskal, S., **Compans, MC.**, Väisänen, H., 2026, Miscarriage reporting in the UK in longitudinal and cross-sectional household surveys, https://doi.org/10.31235/osf.io/e86sp_v1

- **Compans, MC.**, Malmanche, H., Väisänen, H., 2026, Clinical and sociodemographic determinants of miscarriage hospitalisation: Evidence from French healthcare records, https://doi.org/10.31235/osf.io/ud76b_v1
    
- **Compans, MC.**, Malmanche, H., Väisänen, H., 2026, Social  and  health  risk  factors for miscarriage:  a  population-based  study using French healthcarerecords, https://doi.org/10.31235/osf.io/y3rz7_v1

# Peer-reviewed publications

- **Compans, MC.**, Lazzari, E. and Beaujouan, E., 2026, Perceptions of Medically Assisted Reproduction and Fertility Postponement: Limited Evidence, Critical Questions, *European Journal of Population*, vol 42 (20),  https://doi.org/10.1007/s10680-025-09765-3

- **Compans, MC.**, Beaujouan, E., Trimarchi, A., 2026, Partners’ age differences and first birth transitions by age at first and second union in Europe, *Vienna Yearbook of Population Research*, vol 24, pp. 1-26, https://doi.org/10.1553/p-nk6a-fj74

- **Compans, MC.**, Beaujouan, E., Skirbekk, V., 2025, Time to birth for spontaneous and ART births among infertile groups, *BMC Women's Health*, vol 25 (521), doi: https://doi.org/10.1186/s12905-025-04016-3

- **Compans, MC.** and Väisänen, H., 2025, Social patterns of miscarriage reporting and risk: Insights from survey data in France, *European Journal of Public Health*, ckaf099, http://doi:10.1093/eurpub/ckaf099

-   Setz, I., **Compans, MC.**, Beaujouan, E., 2025, The diffusion of late fertility across European regions (2006–2018), *Population, Space and Place*, vol.31 (4), e70031, http://dx.doi.org/10.1002/psp.70031

- Suero, C., **Compans, MC.**, Beaujouan, E., 2025, Delayed Transitions to Adulthood and Assisted Reproduction :
A Study of Educational Differences in Spain, *Advances in life course research*, doi: https://doi.org/10.1016/j.alcr.2025.100672

-   **Compans, MC.** and Zagel H., 2025, "Medically assisted reproduction and non-normative family forms: legislation and public opinion in Europe". 
*European Societies*, https://doi.org/10.1162/euso_a_00003

- **Compans, MC.**, 2024, "Alignment, anticipation, adaptation or lagging behind? Age-based regulations in assisted reproduction and late fertility", *Population and Development Review*, vol.50 (4), pp.1319-1351, https://doi.org/10.1111/padr.12658

-   Lazzari, E., **Compans, MC**. and Beaujouan, E., 2024, "Change in
    the perceived reproductive age window and delayed fertility in
    Europe", *Population Studies*,vol.79 (1), pp. 81-101, https://doi.org/10.1080/00324728.2023.2298678
    
-   **Compans, MC.**, Beaujouan, E. and Suero C., 2023, "Transitions to
    second birth and birth intervals in France and Spain: time squeeze
    or social norms?", *Comparative Population Studies*, vol.48,
    pp.307-338, https://doi.org/10.12765/CPoS-2023-13

-   **Compans, MC.** and Beaujouan, E., 2022, "From Union Formation to
    First Birth: The Role of Age at First Cohabitation in the Transition
    to Motherhood and Fatherhood", *Population*, vol.77 (3), pp.411-436, 
    https://doi.org/10.3917/popu.2203.043

-   **Compans, MC.**, 2021, "D'un 'problème de santé publique' à un
    'phénomène de société'. Le traitement médiatique des maternités et
    des paternités tardives en France (2001--2019)", *Enfances,
    Familles, Générations*, https://doi.org/10.7202/1090938ar

-   **Compans, MC.**, 2021, "Late motherhood, late fatherhood and
    permanent childlessness in France: Trends by educational level and
    cohorts (1950-1970)", *Demographic Research*, vol.45 (10),
    pp.329-344, https://doi.org/10.4054/DemRes.2021.45.10

# Other publications

-  **Compans, MC.**, 2026, "Naissances hors couple : plus tôt et plus souvent chez les moins diplômé·es", in *L’Étude des relations familiales et
intergénérationnelles 2. Erfi 2, vague 1 (2024)*, Bouchet-Valat, M. \& Toulemon, L. (ed.), Aubervilliers : Institut national d'études
démographiques, p.42-43, doi: 10.48756/ined-1res-2.26. https://erfi2.site.ined.fr/fr/resultats/publications

-  **Compans, MC.** and Beaujouan, E., 2026, "Assistance médicale à la procréation : des familles plus petites et plus tardives", in *L’Étude des relations familiales et
intergénérationnelles 2. Erfi 2, vague 1 (2024)*, Bouchet-Valat, M. \& Toulemon, L. (ed.), Aubervilliers : Institut national d'études
démographiques, p.34-35, doi: 10.48756/ined-1res-2.26. https://erfi2.site.ined.fr/fr/resultats/publications

-   **Compans, MC.**, 2025, "Limites d'âge pour la prise en charge de l'assistance médicale à la procréation : quelles évolutions face à l'augmentation des naissances tardives ?", in *Enfanter. Natalité, démographie et politiques publiques*, Senik, C. (ed.), La Découverte - Fondation pour les sciences sociales p.55-69. [link](https://www.editionsladecouverte.fr/enfanter-9782348087493)

-   **Compans, MC.** and Beaujouan, E., 2023, "Where do couples meet?",
    in *Families in Austria Partnerships, fertility intentions and
    economic situation in challenging times*, Neuwirth, N.,
    Buber-Ennser, I., Fux, B. (eds.), p.10.
    [link](https://www.ggp-austria.at/fileadmin/user_upload/k_ggp_austria/GGPat_Families_in_Austria_2023.pdf)

-   Lazzari, E. and **Compans, MC.**, 2023, "Assisted reproduction:
    prevalence among men and women", in *Families in Austria
    Partnerships, fertility intentions and economic situation in
    challenging times*, Neuwirth, N., Buber-Ennser, I., Fux, B., Fux
    (eds.),
    p.39. [link](https://www.ggp-austria.at/fileadmin/user_upload/k_ggp_austria/GGPat_Families_in_Austria_2023.pdf)
    
-   Beaujouan, E., **Compans, MC.** and Gutmorgeth L., 2023, "Finding a
    viable path to"ageing" fertility in Europe", Policy Insights,
    *Population Europe*.
    [link](https://population-europe.eu/research/policy-insights/finding-viable-path-ageing-fertility-europe)

-   **Compans, MC.**, 2021, "Late mothers and late fathers have a first
    birth with younger partners", N-IUSSP.
    [link](https://www.niussp.org/fertility-and-reproduction/late-mothers-and-late-fathers-have-a-first-birth-with-younger-partners/)

-   Chatot, M., **Compans, MC.**, Quennehen M., Yadan, Z., 2021,
    "Introduction. Dossier : Instituer la famille. Entre parenté et
    parentalité", *Revue des politiques sociales et familiales*,
    vol.139-140, pp.3-8. doi: https://doi.org/10.3917/rpsf.139.0003

-   **Compans, MC.**, 2021, "Is it too late to catch up? Comparing
    female and male fertility changes", PopDigests, *Population
    Europe*.
    [link](https://www.population-europe.eu/research/popdigests/it-too-late-catch)

-   **Compans, MC.**, 2021, "Le déclin de la fertilité : une charge
    inégalement partagée entre hommes et femmes", *The Conversation*.
    [link](https://theconversation.com/le-declin-de-la-fertilite-une-charge-inegalement-partagee-entre-hommes-et-femmes-163689)

# PhD Thesis

Pour qui sonne l'heure ? Devenir père ou mère tardivement à l'épreuve
des normes et de l'âge [*For Whom the Clock Tolls? Becoming a late
father or a late mother facing norms and age*].
[link](https://www.theses.fr/2021PA01H077)

Supervisors : Elise de La Rochebrochard (Ined, Inserm) and Arnaud
Régnier-Loilier (Ined)
